package no.uib.inf112.core.map;

public enum Tiles {

    /* THE ROBOT */
    PLAYERTILE(106),

    /* THE TILE THAT ROBOTS CAN FALL THROUGH */
    VOIDTILE(81),

    /* CONSIDERED TO BE THE TILE A PLAYER CAN STAND ON WITHOUT ANY EXTRA ACTIONS/MOVEMENTS */
    EMPTYTILE(5),

    /* FLAGS */
    FLAG1(85),
    FLAG2(86),
    FLAG3(87),
    FLAG4(88),

    /* WALL TILES */
    WALLTOP(),
    WALLTOPWITHLASER(),
    WALLTOPWITHDOUBLELASER(),
    WALLRIGHT(),
    WALLRIGHTWITHLASER(),
    WALLRIGHTWITHDOUBLELASER(),
    WALLLEFT(),
    WALLLEFTWITHLASER(),
    WALLLEFTWITHDOUBLELASER(),
    WALLBOTTOM(),
    WALLBOTTOMWITHLASER(),
    WALLBOTTOMWITHDOUBLELASER(),

    /* STANDALONE LASERS */
    LASERVERTICAL(),
    LASERHORIZONTAL(),
    DOUBLELASERVERTICAL(),
    DOUBLELASERHORIZONTAL(),

    /* OPTION TILES*/
    //Todo find better names
    HAMMERANDWRENCH(7),
    WRENCH(14),


    /* CONVEYOR TILES */
    CONVEYORRIGHT(),
    CONVEYORLEFT(),
    CONVEYORUP(),
    CONVEYORDOWN(),
    CONVEYORFROMLEFTGOUP(),
    CONVEYORFROMTOPGORIGHT(),
    CONVEYORFROMRIGHTGODOWN(),
    CONVEYORFROMBOTTOMGOLEFT(),
    CONVEYORFROMTOPANDBOTTOMGORIGHT(),
    CONVEYORFROMLEFTANDRIGHTGODOWN(),
    CONVEYORFROMRIGHTGOUP(),
    CONVEYORFROMBOTTOMGORIGHT(),
    CONVEYORFROMLEFTGODOWN(),
    CONVEYORFROMTOPGOLEFT(),
    CONVEYORFROMRIGHTANDLEFTGOUP(),
    CONVEYORFROMTOPANDBOTTOMGOLEFT(),
    CONVEYORRIGHTDOUBLESTEP(),
    CONVEYORLEFTDOUBLESTEP(),
    CONVEYORUPDOUBLESTEP(),
    CONVEYORDOWNDOUBLESTEP(),
    CONVEYORFROMLEFTGOUPDOUBLESTEP(),
    CONVEYORFROMTOPGORIGHTDOUBLESTEP(),
    CONVEYORFROMRIGHTGODOWNDOUBLESTEP(),
    CONVEYORFROMBOTTOMGOLEFTDOUBLESTEP(),
    CONVEYORFROMTOPANDBOTTOMGORIGHTDOUBLESTEP(),
    CONVEYORFROMLEFTANDRIGHTGODOWNDOUBLESTEP(),
    CONVEYORFROMRIGHTGOUPDOUBLESTEP(),
    CONVEYORFROMBOTTOMGORIGHTDOUBLESTEP(),
    CONVEYORFROMLEFTGODOWNDOUBLESTEP(),
    CONVEYORFROMTOPGOLEFTDOUBLESTEP(),
    CONVEYORFROMRIGHTANDLEFTGOUPDOUBLESTEP(),
    CONVEYORFROMTOPANDBOTTOMGOLEFTDOUBLESTEP(),
    CONVEYORFROMRIGHTDOWN(),
    CONVEYORFROMTOPRIGHT(),
    CONVEYORFROMLEFTUP(),
    CONVEYORFROMBOTTOMLEFT(),
    CONVEYORFROMBOTTOMRIGTH(),
    CONVEYORFROMLEFTDOWN(),
    CONVEYORFROMTOPLEFT(),
    CONVEYORFROMRIGHTUP(),
    CONVEYORFROMRIGHTDOWNDOUBLESTEP(),
    CONVEYORFROMTOPRIGHTDOUBLESTEP(),
    CONVEYORFROMLEFTUPDOUBLESTEP(),
    CONVEYORFROMBOTTOMLEFTDOUBLESTEP(),
    CONVEYORFROMBOTTOMRIGTHDOUBLESTEP(),
    CONVEYORFROMLEFTDOWNDOUBLESTEP(),
    CONVEYORFROMTOPLEFTDOUBLESTEP(),
    CONVEYORFROMRIGHTUPDOUBLESTEP();


    private final int id;


    Tiles(int id){
        this.id = id;
    }

}
